### PR TITLE
ACS-8482 Add missing @Validated annotation

### PR DESCRIPTION
**Pull request by damianujma**
This PR is to fix the validation that didn't work at the application startup for some properties e.g. `alfresco.repository`, `hyland-experience.storage`.

Using `@Validated` annotation results in a CGLib proxy being created for a bean so removed `final` from the `Application` class.

### CODE REVIEW

**Review by krdabrowski — APPROVED** [review]
Nice fix!

**Review by dsibilio — COMMENTED** [review]
LGTM!

However, I've noticed that searching for https://github.com/search?q=repo%3AAlfresco%2Fhxinsight-connector%20%22ConfigurationProperties%22&type=code reveals plenty more Configuration beans that are not Validated but sometimes use validation annotations.

Should we seize this opportunity and fix it all in one go? cc: @mpichura

**Comment by damianujma** [comment]
> LGTM!
> 
> However, I've noticed that searching for https://github.com/search?q=repo%3AAlfresco%2Fhxinsight-connector%20%22ConfigurationProperties%22&type=code reveals plenty more Configuration beans that are not Validated but sometimes use validation annotations.
> 
> Should we seize this opportunity and fix it all in one go? cc: @mpichura

@dsibilio In general, the Configurations beans are fine. I added one missing `@Validated` annotation in `InsightPredictionsProperties`.

**Review by dsibilio — APPROVED** [review]

**Comment by mpichura** [comment]
> > LGTM!
> > However, I've noticed that searching for https://github.com/search?q=repo%3AAlfresco%2Fhxinsight-connector%20%22ConfigurationProperties%22&type=code reveals plenty more Configuration beans that are not Validated but sometimes use validation annotations.
> > Should we seize this opportunity and fix it all in one go? cc: @mpichura
> 
> @dsibilio In general, the Configurations beans are fine. I added one missing `@Validated` annotation in `InsightPredictionsProperties`.

If you guys see there's some space for improvements or fixing stuff - feel free to make adjustments.

**Review by mpichura — APPROVED** [review]
LGTM

**Pull request merged**
