### PR TITLE
ACS-6380: [HxI LI] added retry logic to PreSignedUrlRequester

### PR DESCRIPTION
**Pull request by krdabrowski**
ACS-6380: [HxI LI] Upload pdf to S3 - PART II - added retry logic to PreSignedUrlRequester

https://alfresco.atlassian.net/browse/ACS-6380

### CODE REVIEW

**Review by Pawel-608 — COMMENTED** [review]
Hmmm, I would say we should not use `spring-retry` (btw I did not know that something like this exists so good to know ;)) because there is bult-in camel functionality that actually works the same: 
image
(not sure if it will work but I'm pretty sure that we can configure it to work exactly like we want).

Also mixing spring magic with camel magic may give some bad results (have you tried if it will actually retry delivery?)

**Comment by krdabrowski** [comment]
Using Camel built-in retry (redelivery) logic also came to my mind - earlier it didn't work for me, but now when I'm testing this seems to work fine, so I had to do sth wrong.
Regarding Spring Retry I've tested it (even wrote integration tests), everything works fine and it's very easy to test - in the opposite to Camel logic. At least I didn't found yet an easy way how to test these redeliveries, but I'm still playing with it.

**Comment by tpage-alfresco** [comment]
On the subject of Camel retry vs Spring retry - FWIW we're using a combination of both in the ESC. I think this is slightly easier to understand than some of the Camel exception handling in ESC, but maybe I'm not comparing like-for-like. Anyway - I'm happy with this the way it is, if you want to rework it with Camel then I'm happy to see that too.

**Review by Pawel-608 — APPROVED** [review]
@tpage-alfresco @krdabrowski I am approving it then

**Pull request merged**
