### PR TITLE
ACS-8177: handle permission updates in live ingester

### PR DESCRIPTION
**Pull request by Pawel-608**

### CODE REVIEW

**Comment by krdabrowski** [comment]
I think it would be good to add new test case in: [UpdateRequestIntegrationTest](https://github.com/Alfresco/hxinsight-connector/blob/dbd4612e458405cbd2e70da6da31687c0a87f6da/live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/domain/usecase/e2e/repository/UpdateRequestIntegrationTest.java)

**Comment by Pawel-608** [comment]
> class

done

**Comment by krdabrowski** [comment]
Still it's good to have this case covered when we already have the tests - thanks!

**Review by krdabrowski — APPROVED** [review]

**Review by azakrzewski-hy — APPROVED** [review]
LGTM

**Pull request merged**
