### PR TITLE
ACS-6392 Predictions E2E.

### PR DESCRIPTION
**Pull request by tpage-alfresco**
Integrate with Hx Insight API and ACS to pass predictions through.

### CODE REVIEW

**Review by azakrzewski-hy — APPROVED** [review]
LGTM

**Review by mpichura — CHANGES_REQUESTED** [review]
Looks like we'd need to wait until Pawel's work is finished before we can merge it.

**Review by Pawel-608 — COMMENTED** [review]
I'm not convinced by this way of writing tests: https://github.com/Alfresco/hxinsight-connector/pull/307#discussion_r1576452138

**Comment by tpage-alfresco** [comment]
We agreed in the stand up to merge this and then make further changes on top.

**Pull request merged**
